export const siteConfig = {
  title: {
    default: "AspenUI - UI Components for your react projects",
    template: "AspenUI",
  },
  description:
    "A collection of customizable, open-source components that work seamlessly with your workflow.",
  creator: "Ignacio Figueroa",
  keywords: [
    "UI Components",
    "Web Development",
    "Open Source",
    "React Components",
    "Tailwind CSS",
    "Typescript Components",
    "Next.js UI Kit",
    "Frontend Development",
    "Web Design Kit",
    "Customizable UI Kit",
    "JavaScript UI Kit",
    "Responsive Design Kit",
    "Component Library",
    "UI Kit",
    "Web UI Kit",
    "Tailwind UI Kit",
    "React UI Kit",
    "UI Design System",
    "Frontend UI Elements",
    "Modern Web Development",
    "Tailwind Components",
    "React UI Elements",
    "JavaScript UI Elements",
    "Developer Resources",
  ],
};
